// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BackupConfig mirrors zipbak-cli.json for the desktop client.
 */
export class BackupConfig {
    "host": string;
    "port": number;
    "user": string;
    "password": string;
    "remote_app_dir": string;
    "remote_srv"?: string;
    "remote_state"?: string;
    "remote_source": string;
    "remote_staging"?: string;
    "local_dir": string;
    "max_part_gb": number;
    "part_name_prefix"?: string;
    "task_id"?: string;
    "notify_email"?: string;
    "smtp_host"?: string;
    "smtp_port"?: number;
    "smtp_user"?: string;
    "smtp_password"?: string;
    "known_hosts_file"?: string;

    /** Creates a new BackupConfig instance. */
    constructor($$source: Partial<BackupConfig> = {}) {
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("password" in $$source)) {
            this["password"] = "";
        }
        if (!("remote_app_dir" in $$source)) {
            this["remote_app_dir"] = "";
        }
        if (!("remote_source" in $$source)) {
            this["remote_source"] = "";
        }
        if (!("local_dir" in $$source)) {
            this["local_dir"] = "";
        }
        if (!("max_part_gb" in $$source)) {
            this["max_part_gb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupConfig($$parsedSource as Partial<BackupConfig>);
    }
}

/**
 * BackupTask is one backup job (source path, local dir, zip prefix).
 */
export class BackupTask {
    "id": string;
    "name"?: string;
    "remote_source": string;
    "local_dir": string;
    "part_name_prefix"?: string;

    /** Creates a new BackupTask instance. */
    constructor($$source: Partial<BackupTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("remote_source" in $$source)) {
            this["remote_source"] = "";
        }
        if (!("local_dir" in $$source)) {
            this["local_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupTask instance from a string or object.
     */
    static createFrom($$source: any = {}): BackupTask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupTask($$parsedSource as Partial<BackupTask>);
    }
}

export class JobStatus {
    "running": boolean;
    "phase": string;
    "currentPart": string;
    "localFile": string;
    "totalFiles": number;
    "packedFiles": number;
    "done": boolean;
    "lastError": string;
    "remoteInited": boolean;
    "pendingZip"?: string;
    "prefetchZip"?: string;
    "remoteHint"?: string;
    "maxFileBytes": number;
    "oversizedFileCount": number;
    "timingStartedAtMs"?: number;
    "timingPackedFilesAtStart"?: number;
    "timingEstimatedTotalMs"?: number;
    "downloadBytesDone"?: number;
    "downloadBytesTotal"?: number;
    "downloadSpeedBps"?: number;

    /** Creates a new JobStatus instance. */
    constructor($$source: Partial<JobStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("phase" in $$source)) {
            this["phase"] = "";
        }
        if (!("currentPart" in $$source)) {
            this["currentPart"] = "";
        }
        if (!("localFile" in $$source)) {
            this["localFile"] = "";
        }
        if (!("totalFiles" in $$source)) {
            this["totalFiles"] = 0;
        }
        if (!("packedFiles" in $$source)) {
            this["packedFiles"] = 0;
        }
        if (!("done" in $$source)) {
            this["done"] = false;
        }
        if (!("lastError" in $$source)) {
            this["lastError"] = "";
        }
        if (!("remoteInited" in $$source)) {
            this["remoteInited"] = false;
        }
        if (!("maxFileBytes" in $$source)) {
            this["maxFileBytes"] = 0;
        }
        if (!("oversizedFileCount" in $$source)) {
            this["oversizedFileCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JobStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): JobStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JobStatus($$parsedSource as Partial<JobStatus>);
    }
}

/**
 * LocalPartFile is one backup part zip on disk (complete or in-progress download).
 */
export class LocalPartFile {
    "name": string;
    "path": string;
    "sizeBytes": number;

    /**
     * downloaded | downloading
     */
    "state": string;

    /** Creates a new LocalPartFile instance. */
    constructor($$source: Partial<LocalPartFile> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("state" in $$source)) {
            this["state"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalPartFile instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalPartFile {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalPartFile($$parsedSource as Partial<LocalPartFile>);
    }
}

/**
 * LocalPartListing lists part zips under the configured local_dir.
 */
export class LocalPartListing {
    "localDir": string;
    "files": LocalPartFile[];

    /** Creates a new LocalPartListing instance. */
    constructor($$source: Partial<LocalPartListing> = {}) {
        if (!("localDir" in $$source)) {
            this["localDir"] = "";
        }
        if (!("files" in $$source)) {
            this["files"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalPartListing instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalPartListing {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField1_0($$parsedSource["files"]);
        }
        return new LocalPartListing($$parsedSource as Partial<LocalPartListing>);
    }
}

/**
 * RemoteDirEntry is one selectable directory on the remote Windows host (via SFTP).
 */
export class RemoteDirEntry {
    "name": string;
    "path": string;

    /** Creates a new RemoteDirEntry instance. */
    constructor($$source: Partial<RemoteDirEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteDirEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteDirEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteDirEntry($$parsedSource as Partial<RemoteDirEntry>);
    }
}

/**
 * RemoteDirListing is returned when browsing remote folders in the UI.
 */
export class RemoteDirListing {
    "current_path": string;
    "parent_path": string;
    "entries": RemoteDirEntry[];

    /** Creates a new RemoteDirListing instance. */
    constructor($$source: Partial<RemoteDirListing> = {}) {
        if (!("current_path" in $$source)) {
            this["current_path"] = "";
        }
        if (!("parent_path" in $$source)) {
            this["parent_path"] = "";
        }
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteDirListing instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteDirListing {
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField2_0($$parsedSource["entries"]);
        }
        return new RemoteDirListing($$parsedSource as Partial<RemoteDirListing>);
    }
}

export class SingleFileConfig {
    "remote_file": string;
    "local_dir": string;

    /** Creates a new SingleFileConfig instance. */
    constructor($$source: Partial<SingleFileConfig> = {}) {
        if (!("remote_file" in $$source)) {
            this["remote_file"] = "";
        }
        if (!("local_dir" in $$source)) {
            this["local_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SingleFileConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SingleFileConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SingleFileConfig($$parsedSource as Partial<SingleFileConfig>);
    }
}

export class UpdateCheckResult {
    "available": boolean;
    "enabled": boolean;
    "currentVersion": string;
    "latestVersion": string;
    "releaseName": string;
    "notes": string;
    "releaseURL": string;

    /** Creates a new UpdateCheckResult instance. */
    constructor($$source: Partial<UpdateCheckResult> = {}) {
        if (!("available" in $$source)) {
            this["available"] = false;
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("latestVersion" in $$source)) {
            this["latestVersion"] = "";
        }
        if (!("releaseName" in $$source)) {
            this["releaseName"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("releaseURL" in $$source)) {
            this["releaseURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): UpdateCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateCheckResult($$parsedSource as Partial<UpdateCheckResult>);
    }
}

// Private type creation functions
const $$createType0 = LocalPartFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RemoteDirEntry.createFrom;
const $$createType3 = $Create.Array($$createType2);
