// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function GetActiveTaskID(): $CancellablePromise<string> {
    return $Call.ByID(13539942);
}

export function GetConfig(): $CancellablePromise<model$0.BackupConfig> {
    return $Call.ByID(3851479826).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetConfigPath(): $CancellablePromise<string> {
    return $Call.ByID(1363897937);
}

export function GetJobStatus(): $CancellablePromise<model$0.JobStatus> {
    return $Call.ByID(1974764065).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetLogs(): $CancellablePromise<string[]> {
    return $Call.ByID(1846021615).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetTasks(): $CancellablePromise<model$0.BackupTask[]> {
    return $Call.ByID(2466878342).then(($result: any) => {
        return $$createType4($result);
    });
}

export function InitRemote(cfg: model$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(3706985456, cfg);
}

export function ListLocalParts(cfg: model$0.BackupConfig): $CancellablePromise<model$0.LocalPartListing> {
    return $Call.ByID(3645809583, cfg).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListRemoteDirectories(cfg: model$0.BackupConfig, pathHint: string): $CancellablePromise<model$0.RemoteDirListing> {
    return $Call.ByID(2582555073, cfg, pathHint).then(($result: any) => {
        return $$createType6($result);
    });
}

export function OpenInExplorer(path: string): $CancellablePromise<void> {
    return $Call.ByID(2585297120, path);
}

export function RefreshRemoteStatus(cfg: model$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(1558611067, cfg);
}

export function ResetBackupTask(cfg: model$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(3156408932, cfg);
}

export function SaveConfig(cfg: model$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(1963304967, cfg);
}

export function SaveConnectionConfig(cfg: model$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(1879177323, cfg);
}

export function SavePathsConfig(cfg: model$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(919836141, cfg);
}

export function SaveTasks(tasks: model$0.BackupTask[]): $CancellablePromise<void> {
    return $Call.ByID(541498381, tasks);
}

export function SetActiveTaskID(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3832656834, taskID);
}

/**
 * SetBackupTimingEstimate persists ETA baseline for restore after restart.
 */
export function SetBackupTimingEstimate(estimatedTotalMs: number): $CancellablePromise<void> {
    return $Call.ByID(2076092094, estimatedTotalMs);
}

export function StartBackup(cfg: model$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(918981386, cfg);
}

export function StopBackup(): $CancellablePromise<void> {
    return $Call.ByID(2848228414);
}

export function TestConnection(cfg: model$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(2775952732, cfg);
}

export function TestEmailNotification(cfg: model$0.BackupConfig): $CancellablePromise<void> {
    return $Call.ByID(2179764507, cfg);
}

// Private type creation functions
const $$createType0 = model$0.BackupConfig.createFrom;
const $$createType1 = model$0.JobStatus.createFrom;
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = model$0.BackupTask.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = model$0.LocalPartListing.createFrom;
const $$createType6 = model$0.RemoteDirListing.createFrom;
