// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function GetConfig(): $CancellablePromise<model$0.SingleFileConfig> {
    return $Call.ByID(517096784).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetLogs(): $CancellablePromise<string[]> {
    return $Call.ByID(215969021).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetStatus(): $CancellablePromise<model$0.JobStatus> {
    return $Call.ByID(989369880).then(($result: any) => {
        return $$createType2($result);
    });
}

export function SaveConfig(cfg: model$0.SingleFileConfig): $CancellablePromise<void> {
    return $Call.ByID(2341337029, cfg);
}

export function StartDownload(sshCfg: model$0.BackupConfig, paths: model$0.SingleFileConfig): $CancellablePromise<void> {
    return $Call.ByID(848351282, sshCfg, paths);
}

export function StopDownload(): $CancellablePromise<void> {
    return $Call.ByID(2528050354);
}

// Private type creation functions
const $$createType0 = model$0.SingleFileConfig.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = model$0.JobStatus.createFrom;
