// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as model$0 from "../model/models.js";

export function ApplyUpdate(): $CancellablePromise<void> {
    return $Call.ByID(2501834584);
}

export function CheckForUpdate(): $CancellablePromise<model$0.UpdateCheckResult> {
    return $Call.ByID(2663839645).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetCurrentVersion(): $CancellablePromise<string> {
    return $Call.ByID(1250492226);
}

export function SkipUpdateVersion(version: string): $CancellablePromise<void> {
    return $Call.ByID(1346718575, version);
}

// Private type creation functions
const $$createType0 = model$0.UpdateCheckResult.createFrom;
